stages:
  - install
  - lint
  - test
  - build
  - publish

variables:
  IMAGE_DOCKER: node:18.20.3-slim
  NPM_REGISTRY: "registry.npmjs.org"
  NPM_TOKEN_DEV: $NPM_TOKEN_DEV # Check CICD Variables

include:
  - local: ".gitlab/ci/send_code.yml"

install:
  stage: install
  image: $IMAGE_DOCKER
  script: |
    yarn install
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'devops'"
      when: on_success
    - if: "$CI_COMMIT_REF_NAME == 'develop'"
      when: on_success
    - when: never
  cache:
    policy: pull-push
    untracked: false
    when: on_success
    paths:
      - node_modules/

lint:
  stage: lint
  image: $IMAGE_DOCKER
  script: |
    yarn lint
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'devops'"
      when: on_success
    - if: "$CI_COMMIT_REF_NAME == 'develop'"
      when: on_success
    - when: never
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  needs:
    - install
  dependencies:
    - install
  allow_failure: true

test:
  stage: test
  image: $IMAGE_DOCKER
  script: |
    yarn test
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'devops'"
      when: on_success
    - if: "$CI_COMMIT_REF_NAME == 'develop'"
      when: on_success
    - when: never
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  needs:
    - install
    - lint
  dependencies:
    - install
  allow_failure: true

build:
  stage: build
  image: $IMAGE_DOCKER
  script: |
    yarn build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'devops'"
      when: on_success
    - if: "$CI_COMMIT_REF_NAME == 'develop'"
      when: on_success
    - when: never
  needs:
    - install
    - lint
    - test
  dependencies:
    - install

publish:
  stage: publish
  image: $IMAGE_DOCKER
  script: |
    echo "//$NPM_REGISTRY/:_authToken=$NPM_TOKEN"
    npm publish
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'develop'"
      variables:
        NPM_TOKEN: $NPM_TOKEN_DEV
      when: on_success
    - when: never
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  needs:
    - install
    - lint
    - test
    - build
  dependencies:
    - install

.merge_devops_to_dev:
  stage: post_actions
  image: $IMAGE_MERGER
  script:
    - export PUSH_REPO=$(echo "$CI_REPOSITORY_URL" | sed -e "s|.*@\(.*\)|git@\1|" -e "s|/|:/|" )
    - git remote set-url origin $PUSH_REPO
    - git clone $PUSH_REPO
    - cd $CI_PROJECT_NAME
    - git checkout devops
    - git pull
    - git checkout develop
    - git pull
    - git reset --hard origin/develop
    - git merge --squash devops
    - git commit -am "modified CI"
    - git push origin develop
    - git push origin --delete devops

.before_merge:
  before_script:
    - apk add --update --no-cache openssh git
    - mkdir ~/.ssh/ && touch ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY_GIT" > ~/.ssh/id_rsa
    - chmod -R 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa $CI_SERVER_HOST >> ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git config --global user.email "repo@sfxdx.com"
    - git config --global user.name "IntegralTeam"

Deploy to develop:
  extends:
    - .before_merge
    - .merge_devops_to_dev
  rules:
    - if: '$CI_COMMIT_REF_NAME == "devops"'
      when: manual
  needs: []
